### ISSUE TITLE
Execute-Assembly - weird parsed assembly name

### ISSUE THREAD

**Issue by tbaker57** [rasta-mouse/SharpC2#13]
Hi @rasta-mouse - thanks again for this great project. 

I have a strange error when using Execute-Assembly. For most assemblies it works fine, but for one in particular (https://github.com/GhostPack/Seatbelt) the code in TransactedAssembly.cs here

    public Assembly Load(byte[] assemblyBytes)
    {
        _assemblyName = ParseArray(assemblyBytes); 

returns 's15_0' for _assemblyName instead of the expected 'SeatBelt.exe' (if I build with 'Debugging Information = 'None' then the ParseArray method fails completely as the string pointer is never found and Array.Copy throws an exception on an unaligned copy).

Thinking that I was building it wrong, I tried a pre-built version from https://github.com/Flangvik/SharpCollection and had the same error (with the _assemblyName = 'alue>b__2_0') 

The workaround is to avoid ParseArray in this case and overload the Load() method to take the name of assembly you upload   and then it's all sweet. But I have no idea what's special about SeatBelt which produces such an assembly.

Anyway, thanks again.
Cheers, Tim

**Comment by rasta-mouse** [comment]
@tbaker57 this should be addressed in the latest release.  I didn't dig into why TransactedAssembly wasn't able to parse the name properly - I cheated and just exposed a means of providing the assembly name in the task.

![image](https://user-images.githubusercontent.com/7346521/229311808-eb1172d0-eaa5-456d-bc3c-242ab175eefb.png)

![image](https://user-images.githubusercontent.com/7346521/229311830-c24ef1d3-790a-4c0f-a5d0-bf541af0d806.png)
