### ISSUE TITLE
Cannot build the server. 

### ISSUE THREAD

**Issue by payloads45** [rasta-mouse/SharpC2#14]
The error says that .NET 7.0 is needed whereas the target machine already has the requirement, still, the server does not build. 

![image](https://user-images.githubusercontent.com/111106697/229429418-c2a81da4-dc13-4ef8-bd98-bef8cc0c851f.png)

**Comment by tbaker57** [comment]
You'll need the .net 7.0 SDK (not the runtime) to build. Can you run:

dotnet --list-sdks
dotnet --list-runtimes

?
Cheers, Tim

**Comment by rasta-mouse** [comment]
No reply from OP, closing.
