### ISSUE TITLE
Unable to start HTTP/HTTPs Handler

### ISSUE THREAD

**Issue by d0MeGaSt4** [rasta-mouse/SharpC2#15]
I am attempting to use v1.2.0 of SharpC2. I installed the client app successfully on my Windows 10 VM following the additional instructions from https://learn.microsoft.com/en-us/dotnet/maui/windows/deployment/publish-cli?view=net-maui-6.0. I use a Kali VM for the Teamserver. 

However I get "Unhandled exception" even before I can configure a listener for the beacon/drone. I am able to setup a SMB listener though. Not sure why it fails to allow me to setup a HTTP/HTTPs listener. Clicking on Reload and attempting again gives the same error. Screenshot and version details attached

![SharpC2-HTTP-Listener](https://user-images.githubusercontent.com/3050140/230745502-e01d543c-1981-4bc0-a4a7-684733667180.jpg)

![SMB-Listener](https://user-images.githubusercontent.com/3050140/230745637-045bc141-38a8-46cb-b4ad-fa3d3326c4f4.png)

On a side note when i start the Teamserver I get no confirmation of the certificate hash either. But I do get a prompt when i connect from the client. 

![Login](https://user-images.githubusercontent.com/3050140/230745723-0bf820d7-6cdf-4100-b7ba-f113631bed6e.png)

**Comment by rasta-mouse** [comment]
Thanks, I think I forgot to have the default C2 profile moved to the build directory.  Should be an easy fix.
