### ISSUE TITLE
Readthedocs link

### ISSUE THREAD

**Issue by tbaker57** [rasta-mouse/SharpC2#4]
Hi @rasta-mouse ,

Do you know where we can find the latest doco on SharpC2 ? The readthedocs link points to https://sharpc2.readthedocs.io/en/latest/ which is "_a Python library for cooks and food lovers that creates recipes mixing random ingredients_". While that sounds interesting (and delicious!) I'd love to be able to find more detailed information about SharpC2.

Cheers, Tim

**Comment by rasta-mouse** [comment]
Yeah, that site is just a placeholder.  I abstained from writing any real docs until the GUI client was finished because I didn't want to redo a bunch of work.
