### ISSUE TITLE
Client cannot compile

### ISSUE THREAD

**Issue by Goworlds** [rasta-mouse/SharpC2#7]
/usr/share/dotnet/sdk/7.0.102/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1147: To build this project, the following workloads must be installed: maui-tizen [/root/SharpC2/Client/Client.csproj]
/usr/share/dotnet/sdk/7.0.102/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1147: To install these workloads, run the following command: dotnet workload restore [/root/SharpC2/Client/Client.csproj]

**Comment by rasta-mouse** [comment]
What OS is this on?  Could you provide the actual command you used to try and build it?

**Comment by Goworlds** [comment]
ubuntu 22 dotnet publish -c Release -r linux-x64 --self-contained

**Comment by rasta-mouse** [comment]
There is currently no support to run .NET MAUI apps on Linux.  Windows and macOS only at this time.
