### ISSUE TITLE
Cannot run SharpC2.exe

### ISSUE THREAD

**Issue by seeworlds** [rasta-mouse/SharpC2#9]
![image](https://user-images.githubusercontent.com/121713113/213419363-1ad62707-0986-44b5-bccd-7bce1db26b27.png)
But I can debug and run
![image](https://user-images.githubusercontent.com/121713113/213419582-1be175da-e458-4ebf-9494-1029e03f64c0.png)

**Comment by rasta-mouse** [comment]
This isn't how .NET MAUI apps are designed to run.  I suggest you look at the documentation for publishing a release build.
https://learn.microsoft.com/en-us/dotnet/maui/windows/deployment/publish-cli?view=net-maui-6.0
